### ISSUE TITLE
Update frontpage logos

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/InvenioRDM-at-NU#409]
- [x] @carsonicator will provide the NUCATS logo and @fenekku will add it
- [x] @carsonicator will crop the new COAR logo and @fenekku will add it
- [x] @carsonicator and @kristiholmes will provide a new CD2H logo and @fenekku will add it
 
![COAR_new_logo](https://user-images.githubusercontent.com/1932651/62804703-a87a2400-bab3-11e9-9449-f1ccaf5ef297.jpg)

**Comment by carsonicator** [comment]
Let's scale down the COAR image to be more in line with the NUCATS and CD2H logos.
