### ISSUE TITLE
Collections and IIIF

### ISSUE THREAD

**Issue by saragon02** [galterlibrary/InvenioRDM-at-NU#487]
Request from Special Collections: can we set up the IIIF viewer for Collections so that a user can swipe through every image in the collection, even if the images come from different records and different resource types?

-Related: when there is no associated image for a record, will there be resource type-specific icon placeholders? (e.g., a document icon, photo icon, movie icon)

**Comment by fenekku** [comment]
Thanks for the input. I am merging this with #270 .

There will not be a default icon for a record with no images. That record would be skipped. We are not planning on incorporating an image to the record/search results like in DigitalHub anymore (currently).
